SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

BUFFER = 20
CHAR_LEN = 17
SCORE_TEXT_WIDTH_EST = 100
SCORE_OFFSET = SCREEN_WIDTH - BUFFER - SCORE_TEXT_WIDTH_EST

SCORE_MODIFIER = 10

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

SHOT_RADIUS = 5